name: 1 Finance Engineering Checklist

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test-and-report:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test engineeringChecklist.spec.js

      - name: Get Allure History
        uses: actions/checkout@v4
        with: 
          ref: gh-pages
          path: gh-pages

      - name: Allure report action from marketplace
        uses: simple-elf/allure-report-action@v1.7
        with: 
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          
  send-mail:
    needs: test-and-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Date Variable
        id: date
        run: echo "::set-output name=date::$(date +'%B %d, %Y')"
      - name: Send email
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Website Engineering Checklist Report - ${{ steps.date.outputs.date }}"
          to: runali.painaik@1finance.co.in, ashish.raykar@1finance.co.in, dakshayani.kasture@1finance.co.in, neshma.chorghe@1finance.co.in, nikhil.bhosle@1finance.co.in, rahul.mandal@1finance.co.in
          from: Runali Painaik <runali.painaik@1finance.co.in>
          body: Build job of ${{github.repository}} completed successfully!
          html_body: file://email.html
