name: 1 Finance Engineering Checklist

on:
  push:
    branches: [main]

jobs:
  test-and-report:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test engineeringChecklist.spec.js

      - name: Generate Allure report
        run: npm run report

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with: 
          ref: gh-pages
          path: gh-pages

      - name: Allure report action from marketplace
        uses: simple-elf/allure-report-action@v1.0  # Replace v1.0 with the appropriate release version/tag
        if: always()
        id: allure-report
        with: 
          allure-results: allure-results
          gh-pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
